### ISSUE TITLE
Option to automatically enter input mode when spawning a `prompt` popup

### ISSUE THREAD

**Issue by hood** [RishabhRD/popfix#20]
As the title implies, it'd be great to automatically enter input mode when entering a `promp`-type popup.

**Comment by hood** [comment]
@RishabhRD any chance I can get an answer on this?

**Comment by RishabhRD** [comment]
Hey sorry! Currently I am not working on it. I am in my final year of my undergrad course and I need to get a good job. So, I am focusing on that. I hope you understand my situation.

**Comment by RishabhRD** [comment]
BTW if this is just for lsp, have a look at my lspactions plugin... It does that automatically. But the plugin is little biased.

**Comment by hood** [comment]
> Hey sorry! Currently I am not working on it. I am in my final year of my undergrad course and I need to get a good job. So, I am focusing on that. I hope you understand my situation. 

No problem my man, good luck on your career! 💪
