### ISSUE TITLE
Not work on Windows

### ISSUE THREAD

**Issue by benawas** [RishabhRD/popfix#3]
Fzy not installed automatically on Windows, there are error in fzy-native.lua on line 30. Is there any help to fix it. I have already try installing Fzy using msys2, but there is still error there.

**Comment by benawas** [comment]
its ok I get fix it using [https://github.com/romgrk/fzy-lua-native/tree/master/static](url).

**Comment by RishabhRD** [comment]
Yeah! I should have checked for operating system while setting default sorter. Would do it in some time. Thanks for reporting🙂

**Comment by MurdeRMelodY** [comment]
How do you fix it?

**Comment by RishabhRD** [comment]
fzy is default sorter now for every operating system! Native fzy is faster
however, it is not stable yet and windows compatibility is not there.
Making it default was my mistake.

So, I have made fzy sorter as default for the time being. Anyone interested
can use native sorter if they want. There is always option to provide your own
sorter.
