### ISSUE TITLE
E5108: Error executing lua .../nvim/pack/packer/start/popfix/lua/popfix/fzy-native.lua:30: dlopen(..../popfix/lua/popfix//lib fzy-darwin-x86_64.so, 5): image not found

### ISSUE THREAD

**Issue by ahmedelgabri** [RishabhRD/popfix#6]
After updating I'm getting this error every time I open neovim, notice that the path contains `//` before the filename at the end.

```
E5108: Error executing lua .../nvim/pack/packer/start/popfix/lua/popfix/fzy-native.lua:30: dlopen(/Users/ahmed/.config/nvim/pack/packer/start/popfix/lua/popfix//libfzy-darwin-x86_64.so, 5): image not found
```

**Comment by RishabhRD** [comment]
I was leaving an unwanted slash character. It works on linux platform on which
I work so, I missed it. Thanks for reporting. It should be fixed now. :smiley:

**Comment by ahmedelgabri** [comment]
Thanks for the fix, but I'm still getting the same error.

**Comment by ahmedelgabri** [comment]
Ignore that, it was a problem on my side. Your fix works

**Comment by RishabhRD** [comment]
Glad it works!

**Comment by ahmedelgabri** [comment]
I figured what's the issue. The fzy integration is optional (according to the README) but the code assumes it's there. So it breaks. 

So I had to run `make` to make it work and stop complaining.

**Comment by RishabhRD** [comment]
@ahmedelgabri #7 removes the hard dependency of native fzy sorter for project.
It also includes install_native_fzy_sorter script for easy installation of
native fzy sorter if anyone wants to use it. This makes the whole installation
a seamless process.

Thanks for reporting :smile:
